services:
  cardmaker:
    build: .
    ports:
      - "8000:8000"
      - "631:631"
    env_file: .env
    volumes:
      - ./app:/app/app
      - ./printer:/printer
      - u2net-cache:/root/.u2net
    networks:
      - default
      - nginx-proxy

volumes:
  u2net-cache:

networks:
  nginx-proxy:
    external: true